name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.ts'
      - '**.tsx'
      - '.github/workflows/build.yml'
  pull_request:
    branches: [ master ]

jobs:
  generate-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=moby/buildkit:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          docker buildx build --file Dockerfile.base \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max \
            --output=type=docker \
            -t ghcr.io/${{ github.repository_owner }}/itemated:latest .
          docker push ghcr.io/${{ github.repository_owner }}/itemated:latest

  build:
    needs: generate-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout image
        run: docker pull ghcr.io/${{ github.repository_owner }}/itemated:latest

      - name: Run Build Commands inside Docker Container
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app -w /app \
          ghcr.io/${{ github.repository_owner }}/itemated:latest \
          /bin/bash -c "
            yarn install --frozen-lockfile
            yarn build:lobby
            yarn build:game
          "