name: lint

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - '**.ts'
      - '**.tsx'
      - '**.mjs'
      - '.prettierrc'
      - '.github/workflows/lint.yml'
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: master
        fetch-depth: 0
    - run: corepack enable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: 'yarn.lock'
    - run: yarn install --frozen-lockfile
    - run: yarn ci:lint